### PR TITLE
Creating install target for libraries generated

### PR DESCRIPTION
**Pull request by tassianors**
Signed-off-by: Tassiano Neuhaus <tneuhaus@rossvideo.com>

### CODE REVIEW

**Comment by tassianors** [comment]
Hi guys, my intention with this commit is to allow me to install the libraries generated using the cmake infra instead of working around it and copying it manually.

thanks for your time.

**Comment by garethsb-sony** [comment]
Thank you, Tassiano. Having some install targets is a good idea. I wonder whether we should also be annotating the include directories too?

**Comment by tassianors** [comment]
Hi  Gareth,

I will check what headers are being used outside the repo and add them to
this review latter today.

thanks

  Tassiano Neuhaus
  +1 613 700 3587

**Comment by tassianors** [comment]
hi Gereth, 

I've updated the patch with the installation of the header files that are needed from an external application using the libs produced by this repo, please let me know if the solution is aligned with your expectations.

thanks.

**Comment by garethsb-sony** [comment]
Hi Tassiano,

Thanks. I agree that `install(FILES ...)` using the existing list variables is perfect for now.
I've just tweaked it a little and merged to master. Let me know if this doesn't do what you need!

**Pull request merged**
